Lanette Tyler   
ST554-601   
Spring 2026   
Project 2, Parts 1b and 2

# Project 2

## Introduction   
The purpose of Part 1 of the project is to create a data quality class in pyspark. The python class, called SparkDataCheck, wraps a Spark, SQL-style data frame and provides functionality for cleaning and validating the data frame. The class can take in a Spark, SQL-style data frame through the .\_\_init\_\_ function, a csv file throught the .from_csv class method, or a standard pandas data frame through the .from_pandas_df class method. The class provides validation and summarization methods for numeric and string columns and documents NULL values in columns. The code for SparkDataCheck class is contained in the python script project2_part1.py.

The purpose of Part 2 of the project is to test and demonstrate SparkDataCheck class on the [provided data](https://www4.stat.ncsu.edu/online/datasets/air.csv), which is documented below. The dataset is copied into the working directory.

## Preliminary Data Steps

In [2]:
#import modules
from pyspark.sql import SparkSession
import pandas as pd
import pyspark.sql.functions as F

In [3]:
#create spark session
spark = SparkSession.builder.appName("my_app").config("pyspark.sql.ansi.enabled", "false").getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Warning: Ignoring non-Spark config property: pyspark.sql.ansi.enabled
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/24 22:30:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/03/24 22:30:47 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/03/24 22:30:47 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
26/03/24 22:30:47 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.

# Project 2: Part 1b

In [4]:
#import SparkDataCheck class (project2_part1.py)
import project2_part1

In [5]:
#prep data (starting with air.csv, ending up with updated air_mod.csv and pandas data frame air_pdf)

#read in data, check for -200 values (which represent missing values in this data set)
air_pdf = pd.read_csv("air.csv")
print(air_pdf["T"].min())
print(air_pdf["RH"].min())
print(air_pdf["AH"].min())

#replace -200 values with None, check min values again (no longer -200)
air_pdf = air_pdf.replace(-200, None)
print(air_pdf["T"].min())
print(air_pdf["RH"].min())
print(air_pdf["AH"].min())

#delete first column with problematic problem name (column seems to be an index)
air_pdf = air_pdf.iloc[:, 1:]

#add string columns for demonstrating string column validation method
for i in range(len(air_pdf)):
        if air_pdf.loc[i, "RH"] == None:
               air_pdf.loc[i, "RH_cat"] = None
        elif air_pdf.loc[i, "RH"] >= 50:
               air_pdf.loc[i, "RH_cat"] = "High"
        else:
               air_pdf.loc[i, "RH_cat"] = "Low"
                
for i in range(len(air_pdf)):
        if air_pdf.loc[i, "AH"] == None:
               air_pdf.loc[i, "AH_cat"] = None
        elif air_pdf.loc[i, "AH"] >= 1.03:
               air_pdf.loc[i, "AH_cat"] = "High"
        else:
               air_pdf.loc[i, "AH_cat"] = "Low"

#clean up column names
air_pdf.columns = air_pdf.columns.str.replace(".", "_")
                
#export to air_mod.csv
air_pdf.to_csv("air_mod.csv", index = False)

#take a look at modified data frame
air_pdf.head()

-200.0
-200.0
-200.0
-1.9
9.2
0.1847

,Date,Time,CO(GT),PT08_S1(CO),NMHC(GT),C6H6(GT),PT08_S2(NMHC),NOx(GT),PT08_S3(NOx),NO2(GT),PT08_S4(NO2),PT08_S5(O3),T,RH,AH,RH_cat,AH_cat
0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578,Low,Low
1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255,Low,Low
2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502,High,Low
3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867,High,Low
4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888,High,Low

## Create instance of SparkDataCheck Class from air.csv file and demonstrate methods on it

### Create and view instance

In [6]:
#create an instance
sdc_air = project2_part1.SparkDataCheck.from_csv(spark, "air_mod.csv")

#view the instance
print(sdc_air)
print("\n")
print(sdc_air.df)
print("\n")
sdc_air.df.show(3)

<project2_part1.SparkDataCheck object at 0x7fdd78b655e0>


DataFrame[Date: string, Time: timestamp, CO(GT): double, PT08_S1(CO): int, NMHC(GT): int, C6H6(GT): double, PT08_S2(NMHC): int, NOx(GT): int, PT08_S3(NOx): int, NO2(GT): int, PT08_S4(NO2): int, PT08_S5(O3): int, T: double, RH: double, AH: double, RH_cat: string, AH_cat: string]


+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+
only showing top 3 rows

### Demonstrate .numColVal() method for validating numeric columns   
Check values in a user-selected numeric column to see if they fall within inclusive, user-defined limits. A resulting column of boolean values is appended to the SparkDataCheck object's data frame attribute.

In [7]:
#demonstrate .numColVal method, invalid column name
sdc_air.numColVal("temp", upper_bound = 20, lower_bound = 15)

Please enter a valid column name as a string.

In [8]:
#demonstrate .numColVal method, non-numeric column
sdc_air.numColVal("RH_cat", upper_bound  = 75, lower_bound = 25)

Please enter a column with numeric data.

DataFrame[Date: string, Time: timestamp, CO(GT): double, PT08_S1(CO): int, NMHC(GT): int, C6H6(GT): double, PT08_S2(NMHC): int, NOx(GT): int, PT08_S3(NOx): int, NO2(GT): int, PT08_S4(NO2): int, PT08_S5(O3): int, T: double, RH: double, AH: double, RH_cat: string, AH_cat: string]

In [9]:
#demontrate .numColVal method, no upper or lower bounds entered
sdc_air.numColVal("T")

Please enter a lower and/or upper bound.

DataFrame[Date: string, Time: timestamp, CO(GT): double, PT08_S1(CO): int, NMHC(GT): int, C6H6(GT): double, PT08_S2(NMHC): int, NOx(GT): int, PT08_S3(NOx): int, NO2(GT): int, PT08_S4(NO2): int, PT08_S5(O3): int, T: double, RH: double, AH: double, RH_cat: string, AH_cat: string]

In [10]:
#demonstrate .numColVal method, both upper and lower bounds provided
sdc_air.numColVal("AH", lower_bound = 0.25, upper_bound = 0.75).show(3)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|((AH >= 0.25) AND (AH <= 0.75))|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|                          false|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|                           true|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|                          false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+
only showing top 3 rows

In [11]:
#demonstrate .numColVal, only upper bound provided
sdc_air.numColVal("RH", upper_bound = 50).show(3)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|((AH >= 0.25) AND (AH <= 0.75))|RH <= 50|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|                          false|    true|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|                           true|    true|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|                          false|   false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+
only showing top 3 rows

In [12]:
#demonstrate .numColVal, only lower bound provided
sdc_air.numColVal("T", lower_bound = 0).show(3)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|((AH >= 0.25) AND (AH <= 0.75))|RH <= 50|T >= 0|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|                          false|    true|  true|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|                           true|    true|  true|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|                          false|   false|  true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+
only showing top 3 rows

### Demonstrate .strColVal() method for validating string columns
Check values in a user-selected string column to see if they fall within a user-defined list of string values. A column of boolean values is appended to the sparkDataCheck object's data frame attribute.

In [13]:
#demonstrate .strColVal, invalid column name
sdc_air.strColVal("time", levels = ["High", "Low"])

Please enter a valid column name as a string.

In [14]:
#demonstrate .strColVal, column wrong format (not string)
sdc_air.strColVal("T", levels = ["High", "Low"])

Please enter a column with string data.

DataFrame[Date: string, Time: timestamp, CO(GT): double, PT08_S1(CO): int, NMHC(GT): int, C6H6(GT): double, PT08_S2(NMHC): int, NOx(GT): int, PT08_S3(NOx): int, NO2(GT): int, PT08_S4(NO2): int, PT08_S5(O3): int, T: double, RH: double, AH: double, RH_cat: string, AH_cat: string, ((AH >= 0.25) AND (AH <= 0.75)): boolean, RH <= 50: string, T >= 0: string]

In [15]:
#demonstrate .strColVal method, check for user entered values when all column values are in user entered values
sdc_air.strColVal("RH_cat", levels = ["High", "Low"])

DataFrame[Date: string, Time: timestamp, CO(GT): double, PT08_S1(CO): int, NMHC(GT): int, C6H6(GT): double, PT08_S2(NMHC): int, NOx(GT): int, PT08_S3(NOx): int, NO2(GT): int, PT08_S4(NO2): int, PT08_S5(O3): int, T: double, RH: double, AH: double, RH_cat: string, AH_cat: string, ((AH >= 0.25) AND (AH <= 0.75)): boolean, RH <= 50: string, T >= 0: string, RH_catCheck: boolean]

In [16]:
#RH_catCheck column has been added, values are limited to user-entered values
sdc_air.df.show(3)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|((AH >= 0.25) AND (AH <= 0.75))|RH <= 50|T >= 0|RH_catCheck|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|                          false|    true|  true|       true|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|                           true|    true|  true|       true|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|                          false|   false|  true|       true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+
only showing top 3 rows

In [17]:
#demonstrate .strColVal, check for user entered values when all column values are not user-entered values
sdc_air.strColVal("RH_cat", levels = ["high", "low"])
sdc_air.df.show(3)
#since it's the same column validated as in previous step, new column name is the same and previous RH_catCheck column was replaced

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|((AH >= 0.25) AND (AH <= 0.75))|RH <= 50|T >= 0|RH_catCheck|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|                          false|    true|  true|      false|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|                           true|    true|  true|      false|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|                          false|   false|  true|      false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+
only showing top 3 rows

### Demonstrate .nullCheck() method
Check values in a user-selected column to see if they are NULL. A column of boolean values is appeneded to the sparkDataCheck object's data frame attribute.

In [18]:
sdc_air.nullCheck("Time")
sdc_air.df.show(3)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+----------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|((AH >= 0.25) AND (AH <= 0.75))|RH <= 50|T >= 0|RH_catCheck|TimeIsNull|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+----------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|                          false|    true|  true|      false|     false|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|                           true|    true|  true|      false|     false|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|                          false|   false|  true|      false|     false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+----------+
only showing top 3 rows

In [19]:
sdc_air.nullCheck("T")
sdc_air.df.show(3)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+----------+-------+
|     Date|               Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|((AH >= 0.25) AND (AH <= 0.75))|RH <= 50|T >= 0|RH_catCheck|TimeIsNull|TIsNull|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+----------+-------+
|3/10/2004|2026-03-24 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|                          false|    true|  true|      false|     false|  false|
|3/10/2004|2026-03-24 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|                           true|    true|  true|      false|     false|  false|
|3/10/2004|2026-03-24 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|                          false|   false|  true|      false|     false|  false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+-------------------------------+--------+------+-----------+----------+-------+
only showing top 3 rows

### Demonstrate .numColSummarizer() method for summarizing numeric data columns

In [20]:
#invalid column name
sdc_air.numColSummarizer(column = "temp")

This is not a valid column name.

In [20]:
#non-numeric column
sdc_air.numColSummarizer(column = "RH_cat")

Please enter a column with numeric data.

In [21]:
#one column input, no grouping variable
sdc_air.numColSummarizer(column = "NMHC(GT)")

   min(NMHC(GT))  max(NMHC(GT))
0              7           1189

In [22]:
#one column input, with grouping variable
sdc_air.numColSummarizer(column = "NMHC(GT)", gr_var = "RH_cat")

  RH_cat  min(NMHC(GT))  max(NMHC(GT))
0   High              7           1129
1    Low              9           1189
2   None             66            512

In [23]:
#no column input, without grouping variable
sdc_air.numColSummarizer()

26/03/24 22:33:21 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

,summary,CO(GT),PT08_S1(CO),NMHC(GT),C6H6(GT),PT08_S2(NMHC),NOx(GT),PT08_S3(NOx),NO2(GT),PT08_S4(NO2),PT08_S5(O3),T,RH,AH
0,min,0.1,647,7,0.1,383,2,322,2,551,221,-1.9,9.2,0.1847
1,max,11.9,2040,1189,63.7,2214,1479,2683,340,2775,2523,44.6,88.7,2.231

In [24]:
#no column input, with grouping variable
sdc_air.numColSummarizer(gr_var = "RH_cat")

,RH_cat,min(CO(GT)),min(PT08_S1(CO)),min(NMHC(GT)),min(C6H6(GT)),min(PT08_S2(NMHC)),min(NOx(GT)),min(PT08_S3(NOx)),min(NO2(GT)),min(PT08_S4(NO2)),...,max(C6H6(GT)),max(PT08_S2(NMHC)),max(NOx(GT)),max(PT08_S3(NOx)),max(NO2(GT)),max(PT08_S4(NO2)),max(PT08_S5(O3)),max(T),max(RH),max(AH)
0,High,0.1,678.0,7,0.1,383.0,2,322.0,2,669.0,...,63.7,2214.0,1479,2095.0,322,2775.0,2523.0,29.8,88.7,2.2310
1,Low,0.1,647.0,9,0.2,387.0,4,330.0,8,551.0,...,44.7,1866.0,1290,2683.0,333,2691.0,2475.0,44.6,49.9,2.1144
2,None,0.3,NaN,66,NaN,NaN,21,NaN,35,NaN,...,NaN,NaN,1310,NaN,340,NaN,NaN,NaN,NaN,NaN

### Demonstrate .strColSummarizer() method for summarizing string data columns

In [26]:
#invalid column name
sdc_air.strColSummarizer(columns = ["rh_cat"])

Please enter a valid column name.

In [26]:
#not string data type
sdc_air.strColSummarizer(columns = ["Time"])

This column is not string type data. Please enter a column of string data type.

In [27]:
#enter one column
sdc_air.strColSummarizer(columns = ["RH_cat"])

  RH_cat  count
0   High   4408
1    Low   4583
2   None    366

In [28]:
#two columns entered, but only one string data type column
sdc_air.strColSummarizer(columns = ["RH_cat", "T"])

  RH_cat  count
0   High   4408
1    Low   4583
2   None    366

In [29]:
#two string columns entered
sdc_air.strColSummarizer(columns = ["RH_cat", "AH_cat"])

  RH_cat AH_cat  count
0   None   None    366
1   High    Low   2242
2    Low    Low   2581
3    Low   High   2002
4   High   High   2166

## Create an instance of SparkDataCheck Class from pandas data frame and demonstrate one method call

In [30]:
#create an instance from pandas data frame
sdc_air2 = project2_part1.SparkDataCheck.from_pandas_df(spark, air_pdf)
sdc_air2.df.show(3)

+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+
|     Date|    Time|CO(GT)|PT08_S1(CO)|NMHC(GT)|C6H6(GT)|PT08_S2(NMHC)|NOx(GT)|PT08_S3(NOx)|NO2(GT)|PT08_S4(NO2)|PT08_S5(O3)|   T|  RH|    AH|RH_cat|AH_cat|
+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+
|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|   Low|   Low|
|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|   Low|   Low|
|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|  High|   Low|
+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------+------+
only showing top 3 rows

In [31]:
#demonstrate a method call
sdc_air2.numColSummarizer(column = "PT08_S5(O3)")

   min(PT08_S5(O3))  max(PT08_S5(O3))
0               221              2523

# Project 2: Part 2

## Introduction
The purpose of Part 2 of the project is to do some basic analysis of the provided weekly NFL data set  in spark, using each API: pandas-on-Spark and Spark SQL. The

## Preliminary Data Steps

In [32]:
#import modules
import pandas as pd
import numpy as np
import pyspark.pandas as ps
ps.set_option("compute.fail_on_ansi_mode", False)

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(

## Pandas-on-Spark

In [33]:
#read in csv file in pandas, then covert to pandas-on-Spark
nfl_data_pd = pd.read_csv("weekly_nfl_data.csv") #pandas data frame
nfl_data_ps = ps.from_pandas(nfl_data_pd) #pandas-on-Spark data frame
nfl_data_ps.head(5) #show first five values

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

In [34]:
#report column names
nfl_data_ps.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

In [35]:
#subset data to QB's, 2005 to 2023, for regular season and specified cols
#summarize data: grouped by name and season, sums and means for other vars
nfl_summary = nfl_data_ps.loc[(nfl_data_ps.position == "QB") & \
                (nfl_data_ps.season >= 2005) & 
                (nfl_data_ps.season_type == "REG"), \
                ["player_display_name", "season", "week", "completions", 
                "attempts", "passing_yards", "passing_tds", "interceptions"]] \
    .groupby(["player_display_name", "season"]) \
    .agg(sum_week = ("week", "sum"), mean_week = ("week", "mean"),
         sum_completions = ("completions", "sum"),
         mean_completions = ("completions", "mean"),
         sum_attempts = ("attempts", "sum"),
         mean_attempts = ("attempts", "mean"),
         sum_passing_yards = ("passing_yards", "sum"), 
         mean_passing_yards = ("passing_yards", "mean"),
         sum_passing_tds = ("passing_tds", "sum"), 
         mean_passing_tds = ("passing_tds", "mean"),
         sum_interceptions = ("interceptions", "sum"), 
         mean_interceptions = ("interceptions", "mean"))
nfl_summary.head()

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                            sum_week  mean_week  sum_completions  mean_completions  sum_attempts  mean_attempts  sum_passing_yards  mean_passing_yards  sum_passing_tds  mean_passing_tds  sum_interceptions  mean_interceptions
player_display_name season
Jeff Blake          2005          19   9.500000                8          4.000000             9       4.500000               55.0           27.500000                1          0.500000                0.0            0.000000
Daunte Culpepper    2005          31   4.428571              139         19.857143           216      30.857143             1564.0          223.428571                6          0.857143               12.0            1.714286
Kerry Collins       2005         134   8.933333              302         20.133333           566      37.733333             3759.0          250.600000               20          1.333333               13.0            0.866667
Tony Banks          2005          17  17.000000               14         14.000000            25      25.000000              173.0          173.000000                1          1.000000                2.0            2.000000
Charlie Batch       2005          35  11.666667               23          7.666667            36      12.000000              246.0           82.000000                1          0.333333                1.0            0.333333

This chart (above) shows the sums and means of weekly quarterback statistics in the NFL for the years 2005 to 2023.

In [36]:
#replace zeros with nan for attempts and interceptions to avoid division
#by zero resulting in inf values and downstream problems later
nfl_summary["sum_attempts"] = nfl_summary["sum_attempts"].replace(0.0, np.nan)
nfl_summary["sum_interceptions"] = nfl_summary["sum_interceptions"].replace(0.0, np.nan)
nfl_summary.head()

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                            sum_week  mean_week  sum_completions  mean_completions  sum_attempts  mean_attempts  sum_passing_yards  mean_passing_yards  sum_passing_tds  mean_passing_tds  sum_interceptions  mean_interceptions
player_display_name season
Jeff Blake          2005          19   9.500000                8          4.000000           9.0       4.500000               55.0           27.500000                1          0.500000                NaN            0.000000
Daunte Culpepper    2005          31   4.428571              139         19.857143         216.0      30.857143             1564.0          223.428571                6          0.857143               12.0            1.714286
Kerry Collins       2005         134   8.933333              302         20.133333         566.0      37.733333             3759.0          250.600000               20          1.333333               13.0            0.866667
Tony Banks          2005          17  17.000000               14         14.000000          25.0      25.000000              173.0          173.000000                1          1.000000                2.0            2.000000
Charlie Batch       2005          35  11.666667               23          7.666667          36.0      12.000000              246.0           82.000000                1          0.333333                1.0            0.333333

In [37]:
#add new columns
nfl_summary["completion_percentage"] = nfl_summary["sum_completions"] \
                                       .div(nfl_summary[("sum_attempts")])
nfl_summary["td_int_ratio"] = nfl_summary["sum_passing_tds"] \
                              .div(nfl_summary["sum_interceptions"])
nfl_summary.head() #view nfl summary object
#notice NaN value for sum_interceptions (in place of zero) causing NaN value 
#for td_int_ratio in top row to avoid problems from inf value at touchdown-to
#interception ratio

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                            sum_week  mean_week  sum_completions  mean_completions  sum_attempts  mean_attempts  sum_passing_yards  mean_passing_yards  sum_passing_tds  mean_passing_tds  sum_interceptions  mean_interceptions  completion_percentage  td_int_ratio
player_display_name season
Jeff Blake          2005          19   9.500000                8          4.000000           9.0       4.500000               55.0           27.500000                1          0.500000                NaN            0.000000               0.888889           NaN
Daunte Culpepper    2005          31   4.428571              139         19.857143         216.0      30.857143             1564.0          223.428571                6          0.857143               12.0            1.714286               0.643519      0.500000
Kerry Collins       2005         134   8.933333              302         20.133333         566.0      37.733333             3759.0          250.600000               20          1.333333               13.0            0.866667               0.533569      1.538462
Tony Banks          2005          17  17.000000               14         14.000000          25.0      25.000000              173.0          173.000000                1          1.000000                2.0            2.000000               0.560000      0.500000
Charlie Batch       2005          35  11.666667               23          7.666667          36.0      12.000000              246.0           82.000000                1          0.333333                1.0            0.333333               0.638889      1.000000

This table (above) shows the additional summary columns of computed values for completion_percentage and td_int_ratio, both calculations of a quarterback's success.

In [38]:
#subset summary to rows with sum_attempts of at least 50
nfl_summary.loc[nfl_summary.sum_attempts >= 50].head()

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                            sum_week  mean_week  sum_completions  mean_completions  sum_attempts  mean_attempts  sum_passing_yards  mean_passing_yards  sum_passing_tds  mean_passing_tds  sum_interceptions  mean_interceptions  completion_percentage  td_int_ratio
player_display_name season
Daunte Culpepper    2005          31   4.428571              139         19.857143         216.0      30.857143             1564.0          223.428571                6          0.857143               12.0            1.714286               0.643519      0.500000
Kerry Collins       2005         134   8.933333              302         20.133333         566.0      37.733333             3759.0          250.600000               20          1.333333               13.0            0.866667               0.533569      1.538462
Jeff Garcia         2005          69  11.500000              102         17.000000         173.0      28.833333              937.0          156.166667                3          0.500000                6.0            1.000000               0.589595      0.500000
Brett Favre         2005         147   9.187500              372         23.250000         607.0      37.937500             3881.0          242.562500               20          1.250000               29.0            1.812500               0.612850      0.689655
Todd Bouman         2005          60  12.000000               68         13.600000         122.0      24.400000              722.0          144.400000                2          0.400000                7.0            1.400000               0.557377      0.285714

In [39]:
#sort by descending completion_percentage
nfl_summary.loc[nfl_summary.sum_attempts >= 50].dropna(subset = "completion_percentage") \
    .sort_values(by = "completion_percentage", ascending = False).head(40)

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                            sum_week  mean_week  sum_completions  mean_completions  sum_attempts  mean_attempts  sum_passing_yards  mean_passing_yards  sum_passing_tds  mean_passing_tds  sum_interceptions  mean_interceptions  completion_percentage  td_int_ratio
player_display_name season
C.J. Beathard       2023          65  10.833333               40          6.666667          53.0       8.833333              349.0           58.166667                1          0.166667                NaN            0.000000               0.754717           NaN
Colt McCoy          2021          62   8.857143               74         10.571429          99.0      14.142857              740.0          105.714286                3          0.428571                1.0            0.142857               0.747475      3.000000
Matt Schaub         2019          52  10.400000               50         10.000000          67.0      13.400000              580.0          116.000000                3          0.600000                1.0            0.200000               0.746269      3.000000
Drew Brees          2018         130   8.666667              364         24.266667         489.0      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
                    2019         119  10.818182              281         25.545455         378.0      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
Mason Rudolph       2023          66  16.500000               55         13.750000          74.0      18.500000              719.0          179.750000                3          0.750000                NaN            0.000000               0.743243           NaN
Taysom Hill         2020         147   9.187500               88          5.500000         121.0       7.562500              928.0           58.000000                4          0.250000                2.0            0.125000               0.727273      2.000000
Nick Foles          2018          51  10.200000              141         28.200000         195.0      39.000000             1413.0          282.600000                7          1.400000                4.0            0.800000               0.723077      1.750000
Drew Brees          2017         148   9.250000              386         24.125000         536.0      33.500000             4334.0          270.875000               23          1.437500                8.0            0.500000               0.720149      2.875000
Sam Bradford        2016         146   9.733333              395         26.333333         552.0      36.800000             3877.0          258.466667               20          1.333333                5.0            0.333333               0.715580      4.000000
Drew Brees          2011         142   8.875000              471         29.437500         660.0      41.250000             5535.0          345.937500               46          2.875000               14.0            0.875000               0.713636      3.285714
Colt McCoy          2014          57  11.400000               91         18.200000         128.0      25.600000             1057.0          211.400000                4          0.800000                3.0            0.600000               0.710938      1.333333
Aaron Rodgers       2020         148   9.250000              372         23.250000         526.0      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
Bailey Zappe        2022          22   5.500000               65         16.250000          92.0      23.000000              781.0          195.250000                5          1.250000                3.0            0.750000               0.706522      1.666667
Drew Brees          2009         131   8.733333              363         24.200000         514.0      34.266667             4388.0          292.533333               34          2.266667               11.0            0.733333               0.706226      3.090909
                    2020          97   8.083333              275         22.916667         390.0      32.500000             2942.0          245.166667               24          2.000000                6.0            0.500000               0.705128      4.000000
Joe Burrow          2021         143   8.937500              366         22.875000         520.0      32.500000             4611.0          288.187500               34          2.125000               14.0            0.875000               0.703846      2.428571
Derek Carr          2019         147   9.187500              361         22.562500         513.0      32.062500             4054.0          253.375000               21          1.312500                8.0            0.500000               0.703704      2.625000
Jake Browning       2023         117  13.000000              171         19.000000         243.0      27.000000             1936.0          215.111111               12          1.333333                7.0            0.777778               0.703704      1.714286
Chase Daniel        2019          20   6.666667               45         15.000000          64.0      21.333333              435.0          145.000000                3          1.000000                2.0            0.666667               0.703125      1.500000
Ryan Tannehill      2019         128  10.666667              201         16.750000         286.0      23.833333             2742.0          228.500000               22          1.833333                6.0            0.500000               0.702797      3.666667
Deshaun Watson      2020         145   9.062500              382         23.875000         544.0      34.000000             4823.0          301.437500               33          2.062500                7.0            0.437500               0.702206      4.714286
Alex Smith          2012          63   6.300000              153         15.300000         218.0      21.800000             1737.0          173.700000               13          1.300000                5.0            0.500000               0.701835      2.600000
Kirk Cousins        2018         143   8.937500              425         26.562500         606.0      37.875000             4298.0          268.625000               30          1.875000               10.0            0.625000               0.701320      3.000000
Jamie Martin        2005          92  11.500000              124         15.500000         177.0      22.125000             1277.0          159.625000                5          0.625000                7.0            0.875000               0.700565      0.714286
Drew Brees          2016         148   9.250000              471         29.437500         673.0      42.062500             5208.0          325.500000               37          2.312500               15.0            0.937500               0.699851      2.466667
Tony Romo           2014         133   8.866667              304         20.266667         435.0      29.000000             3705.0          247.000000               34          2.266667                9.0            0.600000               0.698851      3.777778
Matt Ryan           2016         142   8.875000              373         23.312500         534.0      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
Kirk Cousins        2015         145   9.062500              379         23.687500         543.0      33.937500             4166.0          260.375000               29          1.812500               11.0            0.687500               0.697974      2.636364
Geno Smith          2022         160   9.411765              399         23.470588         572.0      33.647059             4282.0          251.882353               30          1.764706               11.0            0.647059               0.697552      2.727273
Chase Daniel        2018          38   9.500000               53         13.250000          76.0      19.000000              515.0          128.750000                3          0.750000                2.0            0.500000               0.697368      1.500000
Carson Wentz        2018          93   8.454545              279         25.363636         401.0      36.454545             3074.0          279.454545               21          1.909091                7.0            0.636364               0.695761      3.000000
Dak Prescott        2023         164   9.647059              410         24.117647         590.0      34.705882             4516.0          265.647059               36          2.117647                9.0            0.529412               0.694915      4.000000
Philip Rivers       2013         145   9.062500              378         23.625000         544.0      34.000000             4478.0          279.875000               32          2.000000               11.0            0.687500               0.694853      2.909091
Tony Romo           2010          24   4.000000              148         24.666667         213.0      35.500000             1605.0          267.500000               11          1.833333                7.0            1.166667               0.694836      1.571429
Kirk Cousins        2023          36   4.500000              216         27.000000         311.0      38.875000             2331.0          291.375000               18          2.250000                5.0            0.625000               0.694534      3.600000
Matt Ryan           2018         145   9.062500              422         26.375000         608.0      38.000000             4924.0          307.750000               35          2.187500                7.0            0.437500               0.694079      5.000000
Brock Purdy         2023         144   9.000000              308         19.250000         444.0      27.750000             4280.0          267.500000               31          1.937500               11.0            0.687500               0.693694      2.818182
Jim Sorgi           2005          57  11.400000               43          8.600000          62.0      12.400000              444.0           88.800000                3          0.600000                1.0            0.200000               0.693548      3.000000
Brandon Weeden      2015          45   7.500000               97         16.166667         140.0      23.333333             1043.0          173.833333                5          0.833333                2.0            0.333333               0.692857      2.500000

In this table (above) we see a ranked list of quarterback's seasons, according to their completion percentage. The completion percentage is the sum of touchdowns over the sum of attempts, showing the percentage of the quarteback's attempts resulted in touchdowns. The highest ranked quarterback season by completion percentage was C.J. Beathard in 2023. Drew Brees is also notable for having seven of the top 40 quarterback seasons by completion percentage.

In [40]:
#sort by descending td_int_ratio
nfl_summary.loc[nfl_summary.sum_attempts >= 50].dropna(subset = "td_int_ratio") \
    .sort_values(by = "td_int_ratio", ascending = False).head(40)

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                            sum_week  mean_week  sum_completions  mean_completions  sum_attempts  mean_attempts  sum_passing_yards  mean_passing_yards  sum_passing_tds  mean_passing_tds  sum_interceptions  mean_interceptions  completion_percentage  td_int_ratio
player_display_name season
Tom Brady           2016         134  11.166667              291         24.250000         432.0      36.000000             3554.0          296.166667               28          2.333333                2.0            0.166667               0.673611     14.000000
Nick Foles          2013         129   9.923077              203         15.615385         317.0      24.384615             2891.0          222.384615               27          2.076923                2.0            0.153846               0.640379     13.500000
Josh McCown         2013          92  11.500000              149         18.625000         224.0      28.000000             1829.0          228.625000               13          1.625000                1.0            0.125000               0.665179     13.000000
Aaron Rodgers       2018         146   9.125000              372         23.250000         597.0      37.312500             4442.0          277.625000               25          1.562500                2.0            0.125000               0.623116     12.500000
Damon Huard         2006          69   6.900000              148         14.800000         244.0      24.400000             1878.0          187.800000               11          1.100000                1.0            0.100000               0.606557     11.000000
Aaron Rodgers       2020         148   9.250000              372         23.250000         526.0      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
                    2021         149   9.312500              366         22.875000         531.0      33.187500             4115.0          257.187500               37          2.312500                4.0            0.250000               0.689266      9.250000
Tom Brady           2010         148   9.250000              324         20.250000         492.0      30.750000             3900.0          243.750000               36          2.250000                4.0            0.250000               0.658537      9.000000
Jake Delhomme       2007           6   2.000000               55         18.333333          86.0      28.666667              617.0          205.666667                8          2.666667                1.0            0.333333               0.639535      8.000000
Aaron Rodgers       2014         144   9.000000              341         21.312500         520.0      32.500000             4381.0          273.812500               38          2.375000                5.0            0.312500               0.655769      7.600000
                    2011         128   8.533333              342         22.800000         501.0      33.400000             4636.0          309.066667               45          3.000000                6.0            0.400000               0.682635      7.500000
Drew Brees          2019         119  10.818182              281         25.545455         378.0      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
Aaron Rodgers       2019         142   8.875000              353         22.062500         569.0      35.562500             4002.0          250.125000               26          1.625000                4.0            0.250000               0.620387      6.500000
Drew Brees          2018         130   8.666667              364         24.266667         489.0      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
Patrick Mahomes     2020         126   8.400000              390         26.000000         588.0      39.200000             4740.0          316.000000               38          2.533333                6.0            0.400000               0.663265      6.333333
Tom Brady           2007         143   8.937500              398         24.875000         578.0      36.125000             4806.0          300.375000               50          3.125000                8.0            0.500000               0.688581      6.250000
Russell Wilson      2019         142   8.875000              341         21.312500         516.0      32.250000             4110.0          256.875000               31          1.937500                5.0            0.312500               0.660853      6.200000
David Garrard       2007         105   8.750000              208         17.333333         325.0      27.083333             2509.0          209.083333               18          1.500000                3.0            0.250000               0.640000      6.000000
Matthew Stafford    2010          26   6.500000               57         14.250000          96.0      24.000000              535.0          133.750000                6          1.500000                1.0            0.250000               0.593750      6.000000
Lamar Jackson       2019         128   8.533333              265         17.666667         401.0      26.733333             3127.0          208.466667               36          2.400000                6.0            0.400000               0.660848      6.000000
Dak Prescott        2016         146   9.125000              311         19.437500         459.0      28.687500             3667.0          229.187500               23          1.437500                4.0            0.250000               0.677560      5.750000
Aaron Rodgers       2016         149   9.312500              401         25.062500         610.0      38.125000             4428.0          276.750000               40          2.500000                7.0            0.437500               0.657377      5.714286
Peyton Manning      2013         144   9.000000              450         28.125000         659.0      41.187500             5477.0          342.312500               55          3.437500               10.0            0.625000               0.682853      5.500000
Matt Ryan           2016         142   8.875000              373         23.312500         534.0      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
Alex Smith          2017         126   8.400000              341         22.733333         505.0      33.666667             4042.0          269.466667               26          1.733333                5.0            0.333333               0.675248      5.200000
Patrick Mahomes     2019         124   8.857143              319         22.785714         484.0      34.571429             4031.0          287.928571               26          1.857143                5.0            0.357143               0.659091      5.200000
Tom Brady           2015         149   9.312500              402         25.125000         624.0      39.000000             4770.0          298.125000               36          2.250000                7.0            0.437500               0.644231      5.142857
Jeff Garcia         2006         102  12.750000              116         14.500000         188.0      23.500000             1309.0          163.625000               10          1.250000                2.0            0.250000               0.617021      5.000000
Matt Ryan           2018         145   9.062500              422         26.375000         608.0      38.000000             4924.0          307.750000               35          2.187500                7.0            0.437500               0.694079      5.000000
Russell Wilson      2018         146   9.125000              280         17.500000         427.0      26.687500             3448.0          215.500000               35          2.187500                7.0            0.437500               0.655738      5.000000
Geno Smith          2021          26   6.500000               65         16.250000          95.0      23.750000              702.0          175.500000                5          1.250000                1.0            0.250000               0.684211      5.000000
Aaron Rodgers       2012         143   8.937500              371         23.187500         552.0      34.500000             4295.0          268.437500               39          2.437500                8.0            0.500000               0.672101      4.875000
Ryan Tannehill      2020         149   9.312500              315         19.687500         481.0      30.062500             3819.0          238.687500               34          2.125000                7.0            0.437500               0.654886      4.857143
Brett Favre         2009         144   9.000000              364         22.750000         532.0      33.250000             4202.0          262.625000               33          2.062500                7.0            0.437500               0.684211      4.714286
Carson Wentz        2017          95   7.307692              265         20.384615         440.0      33.846154             3296.0          253.538462               33          2.538462                7.0            0.538462               0.602273      4.714286
Deshaun Watson      2020         145   9.062500              382         23.875000         544.0      34.000000             4823.0          301.437500               33          2.062500                7.0            0.437500               0.702206      4.714286
Kirk Cousins        2021         147   9.187500              372         23.250000         561.0      35.062500             4221.0          263.812500               33          2.062500                7.0            0.437500               0.663102      4.714286
Derek Carr          2016         126   8.400000              357         23.800000         560.0      37.333333             3937.0          262.466667               28          1.866667                6.0            0.400000               0.637500      4.666667
Jameis Winston      2021          30   4.285714               95         13.571429         161.0      23.000000             1170.0          167.142857               14          2.000000                3.0            0.428571               0.590062      4.666667
C.J. Stroud         2023         133   8.866667              319         21.266667         499.0      33.266667             4108.0          273.866667               23          1.533333                5.0            0.333333               0.639279      4.600000

In this table (above) we see a ranked list of quarterback's seasons, according to their touchdown to interception ratios. The highest ranked quarterback season by touchdown to interception ratio was Tom Brady in 2016, and he has an additional three seasons in this top 40. Aaron Rodgers is also notable for appearing in the top 40 touchdown to interception ratios seven times. Drew Brees appears on this list twice after appearing on the completion percentage list seven times.

## Spark SQL

In [41]:
nfl_data_sql = spark.read.load("weekly_nfl_data.csv",
                               format = "csv",
                               sep = ",",
                               header = "true")
nfl_data_sql.show(5)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

In [42]:
nfl_data_sql.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

In [43]:
#subset the data raws to QB, 2005 to 2023, and specified columns
nfl_data_sql.filter((nfl_data_sql.position == "QB") &
                    (nfl_data_sql.season >= 2005) &
                    (nfl_data_sql.season_type == "REG")) \
    .select("player_display_name", "season", "week", "completions",
            "attempts", "passing_yards", "passing_tds", "interceptions").show(5)

+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|player_display_name|season|week|completions|attempts|passing_yards|passing_tds|interceptions|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|         Tony Banks|  2005|  17|         14|      25|        173.0|          1|          2.0|
|      Charlie Batch|  2005|   9|          9|      16|         65.0|          0|          1.0|
|      Charlie Batch|  2005|  10|         13|      19|        150.0|          0|          0.0|
|      Charlie Batch|  2005|  16|          1|       1|         31.0|          1|          0.0|
|         Jeff Blake|  2005|   2|          1|       1|         11.0|          0|          0.0|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
only showing top 5 rows

In [44]:
#look at column names and data types for the subset
nfl_data_sql.filter((nfl_data_sql.position == "QB") &
                    (nfl_data_sql.season >= 2005) &
                    (nfl_data_sql.season_type == "REG")) \
    .select("player_display_name", "season", "week", "completions",
            "attempts", "passing_yards", "passing_tds", "interceptions")

DataFrame[player_display_name: string, season: string, week: string, completions: string, attempts: string, passing_yards: string, passing_tds: string, interceptions: string]

In [45]:
#numeric data was read in as strings, let's fix it
nfl_data_sql = nfl_data_sql.withColumn("week", F.col("week").cast("int"))
nfl_data_sql = nfl_data_sql.withColumn("completions", F.col("completions").cast("int"))
nfl_data_sql = nfl_data_sql.withColumn("attempts", F.col("attempts").cast("int"))
nfl_data_sql = nfl_data_sql.withColumn("passing_tds", F.col("passing_tds").cast("int"))
nfl_data_sql = nfl_data_sql.withColumn("interceptions", F.col("interceptions").cast("float"))
nfl_data_sql = nfl_data_sql.withColumn("passing_yards", F.col("passing_yards").cast("float"))

In [46]:
#subset the data raws to QB, 2005 to 2023, and specified columns
#with correct data types
nfl_data_sql.filter((nfl_data_sql.position == "QB") &
                    (nfl_data_sql.season >= 2005) &
                    (nfl_data_sql.season_type == "REG")) \
    .select("player_display_name", "season", "week", "completions",
            "attempts", "passing_yards", "passing_tds", "interceptions")

DataFrame[player_display_name: string, season: string, week: int, completions: int, attempts: int, passing_yards: float, passing_tds: int, interceptions: float]

In [47]:
#summarize the subsetted data and create new variables
nfl_data_sql.filter((nfl_data_sql.position == "QB") &
                    (nfl_data_sql.season >= 2005) &
                    (nfl_data_sql.season_type == "REG")) \
    .select("player_display_name", "season", "week", "completions",
            "attempts", "passing_yards", "passing_tds", "interceptions") \
    .groupBy("player_display_name", "season") \
    .agg(F.sum("week"), F.mean("week"),
         F.sum("completions"), F.mean("completions"),
         F.sum("attempts"), F.mean("attempts"),
         F.sum("passing_yards"), F.mean("passing_yards"),
         F.sum("passing_tds"), F.mean("passing_tds"),
         F.sum("interceptions"), F.mean("interceptions")) \
    .withColumn("completion_percentage", 
                F.try_divide(F.col("sum(completions)"), F.col("sum(attempts)"))) \
    .withColumn("td_int_ratio", 
               F.try_divide(F.col("sum(passing_tds)"), F.col("sum(interceptions)"))) \
    .filter(F.col("sum(interceptions)") == 0).show(5)

+-------------------+------+---------+------------------+----------------+------------------+-------------+-----------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------+
|player_display_name|season|sum(week)|         avg(week)|sum(completions)|  avg(completions)|sum(attempts)|    avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|  avg(passing_tds)|sum(interceptions)|avg(interceptions)|completion_percentage|td_int_ratio|
+-------------------+------+---------+------------------+----------------+------------------+-------------+-----------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------+
|    Kordell Stewart|  2005|        9|               9.0|               0|               0.0|            0|              0.0|               0.0|               0.0|               0|               0.0|               0.0|               0.0|                 NULL|        NULL|
|       Chris Weinke|  2005|       31|10.333333333333334|               7|2.3333333333333335|           13|4.333333333333333|              64.0|21.333333333333332|               1|0.3333333333333333|               0.0|               0.0|   0.5384615384615384|        NULL|
|   Vinny Testaverde|  2006|       43|14.333333333333334|               2|0.6666666666666666|            3|              1.0|              29.0| 9.666666666666666|               1|0.3333333333333333|               0.0|               0.0|   0.6666666666666666|        NULL|
|     Patrick Ramsey|  2006|       12|              12.0|               0|               0.0|            1|              1.0|               0.0|               0.0|               0|               0.0|               0.0|               0.0|                  0.0|        NULL|
|       Jamie Martin|  2007|       12|              12.0|               0|               0.0|            0|              0.0|               0.0|               0.0|               0|               0.0|               0.0|               0.0|                 NULL|        NULL|
+-------------------+------+---------+------------------+----------------+------------------+-------------+-----------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------+
only showing top 5 rows

In [48]:
#save subsetted, summarized data with new columns as an object
nfl_summary_sql = nfl_data_sql.filter((nfl_data_sql.position == "QB") &
                    (nfl_data_sql.season >= 2005) &
                    (nfl_data_sql.season_type == "REG")) \
    .select("player_display_name", "season", "week", "completions",
            "attempts", "passing_yards", "passing_tds", "interceptions") \
    .groupBy("player_display_name", "season") \
    .agg(F.sum("week"), F.mean("week"),
         F.sum("completions"), F.mean("completions"),
         F.sum("attempts"), F.mean("attempts"),
         F.sum("passing_yards"), F.mean("passing_yards"),
         F.sum("passing_tds"), F.mean("passing_tds"),
         F.sum("interceptions"), F.mean("interceptions")) \
    .withColumn("completion_percentage", 
                F.try_divide(F.col("sum(completions)"), F.col("sum(attempts)"))) \
    .withColumn("td_int_ratio", 
               F.try_divide(F.col("sum(passing_tds)"), F.col("sum(interceptions)")))
print(nfl_summary_sql)
nfl_summary_sql.show(5)

DataFrame[player_display_name: string, season: string, sum(week): bigint, avg(week): double, sum(completions): bigint, avg(completions): double, sum(attempts): bigint, avg(attempts): double, sum(passing_yards): double, avg(passing_yards): double, sum(passing_tds): bigint, avg(passing_tds): double, sum(interceptions): double, avg(interceptions): double, completion_percentage: double, td_int_ratio: double]
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum(week)|         avg(week)|sum(completions)|  avg(completions)|sum(attempts)|     avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|  avg(passing_tds)|sum(interceptions)|avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
|     Sage Rosenfels|  2005|       46|              11.5|              34|               8.5|           61|             15.25|             462.0|             115.5|               4|               1.0|               3.0|              0.75|   0.5573770491803278|1.3333333333333333|
|    Joey Harrington|  2006|      118|10.727272727272727|             223|20.272727272727273|          388| 35.27272727272727|            2236.0|203.27272727272728|              12|1.0909090909090908|              15.0|1.3636363636363635|   0.5747422680412371|               0.8|
|        Eli Manning|  2005|      148|              9.25|             294|            18.375|          558|            34.875|            3762.0|           235.125|              24|               1.5|              17.0|            1.0625|   0.5268817204301075| 1.411764705882353|
| Ben Roethlisberger|  2005|      113| 9.416666666666666|             168|              14.0|          268|22.333333333333332|            2385.0|            198.75|              17|1.4166666666666667|               9.0|              0.75|   0.6268656716417911|1.8888888888888888|
|       Chris Weinke|  2006|       45|              15.0|              56|18.666666666666668|           96|              32.0|             625.0|208.33333333333334|               2|0.6666666666666666|               4.0|1.3333333333333333|   0.5833333333333334|               0.5|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 5 rows

Spark SQL handled the issue of division by zero without inf values and division by zero errors. It went straight to NULL values.

In [49]:
#subset the data object to rows of player-season combinations with
#at least 50 sum(attempts)
nfl_summary_sql.filter(nfl_summary_sql["sum(attempts)"] >= 50).show(5)

+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum(week)|         avg(week)|sum(completions)|  avg(completions)|sum(attempts)|     avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|  avg(passing_tds)|sum(interceptions)|avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
|     Sage Rosenfels|  2005|       46|              11.5|              34|               8.5|           61|             15.25|             462.0|             115.5|               4|               1.0|               3.0|              0.75|   0.5573770491803278|1.3333333333333333|
|    Joey Harrington|  2006|      118|10.727272727272727|             223|20.272727272727273|          388| 35.27272727272727|            2236.0|203.27272727272728|              12|1.0909090909090908|              15.0|1.3636363636363635|   0.5747422680412371|               0.8|
|        Eli Manning|  2005|      148|              9.25|             294|            18.375|          558|            34.875|            3762.0|           235.125|              24|               1.5|              17.0|            1.0625|   0.5268817204301075| 1.411764705882353|
| Ben Roethlisberger|  2005|      113| 9.416666666666666|             168|              14.0|          268|22.333333333333332|            2385.0|            198.75|              17|1.4166666666666667|               9.0|              0.75|   0.6268656716417911|1.8888888888888888|
|       Chris Weinke|  2006|       45|              15.0|              56|18.666666666666668|           96|              32.0|             625.0|208.33333333333334|               2|0.6666666666666666|               4.0|1.3333333333333333|   0.5833333333333334|               0.5|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 5 rows

In [50]:
#include only player-season combinations with at leat 50 total attempts
#sort by completion percentage and return top 40 values
nfl_summary_sql.filter(nfl_summary_sql["sum(attempts)"] >= 50) \
    .sort(F.col("completion_percentage").desc_nulls_last()).show(40)

+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+-------------------+------------------+-------------------+---------------------+------------------+
|player_display_name|season|sum(week)|         avg(week)|sum(completions)|  avg(completions)|sum(attempts)|     avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|   avg(passing_tds)|sum(interceptions)| avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+-------------------+------------------+-------------------+---------------------+------------------+
|      C.J. Beathard|  2023|       65|10.833333333333334|              40| 6.666666666666667|           53| 8.833333333333334|             349.0|58.166666666666664|               1|0.16666666666666666|               0.0|                0.0|   0.7547169811320755|              NULL|
|         Colt McCoy|  2021|       62| 8.857142857142858|              74|10.571428571428571|           99|14.142857142857142|             740.0|105.71428571428571|               3|0.42857142857142855|               1.0|0.14285714285714285|   0.7474747474747475|               3.0|
|        Matt Schaub|  2019|       52|              10.4|              50|              10.0|           67|              13.4|             580.0|             116.0|               3|                0.6|               1.0|                0.2|    0.746268656716418|               3.0|
|         Drew Brees|  2018|      130| 8.666666666666666|             364|24.266666666666666|          489|              32.6|            3992.0| 266.1333333333333|              32| 2.1333333333333333|               5.0| 0.3333333333333333|   0.7443762781186094|               6.4|
|         Drew Brees|  2019|      119|10.818181818181818|             281|25.545454545454547|          378| 34.36363636363637|            2979.0| 270.8181818181818|              27| 2.4545454545454546|               4.0|0.36363636363636365|   0.7433862433862434|              6.75|
|      Mason Rudolph|  2023|       66|              16.5|              55|             13.75|           74|              18.5|             719.0|            179.75|               3|               0.75|               0.0|                0.0|   0.7432432432432432|              NULL|
|        Taysom Hill|  2020|      147|            9.1875|              88|               5.5|          121|            7.5625|             928.0|              58.0|               4|               0.25|               2.0|              0.125|   0.7272727272727273|               2.0|
|         Nick Foles|  2018|       51|              10.2|             141|              28.2|          195|              39.0|            1413.0|             282.6|               7|                1.4|               4.0|                0.8|   0.7230769230769231|              1.75|
|         Drew Brees|  2017|      148|              9.25|             386|            24.125|          536|              33.5|            4334.0|           270.875|              23|             1.4375|               8.0|                0.5|   0.7201492537313433|             2.875|
|       Sam Bradford|  2016|      146| 9.733333333333333|             395|26.333333333333332|          552|              36.8|            3877.0|258.46666666666664|              20| 1.3333333333333333|               5.0| 0.3333333333333333|   0.7155797101449275|               4.0|
|         Drew Brees|  2011|      142|             8.875|             471|           29.4375|          660|             41.25|            5535.0|          345.9375|              46|              2.875|              14.0|              0.875|   0.7136363636363636|3.2857142857142856|
|         Colt McCoy|  2014|       57|              11.4|              91|              18.2|          128|              25.6|            1057.0|             211.4|               4|                0.8|               3.0|                0.6|            0.7109375|1.3333333333333333|
|      Aaron Rodgers|  2020|      148|              9.25|             372|             23.25|          526|            32.875|            4299.0|          268.6875|              48|                3.0|               5.0|             0.3125|   0.7072243346007605|               9.6|
|       Bailey Zappe|  2022|       22|               5.5|              65|             16.25|           92|              23.0|             781.0|            195.25|               5|               1.25|               3.0|               0.75|   0.7065217391304348|1.6666666666666667|
|         Drew Brees|  2009|      131| 8.733333333333333|             363|              24.2|          514|34.266666666666666|            4388.0|292.53333333333336|              34| 2.2666666666666666|              11.0| 0.7333333333333333|   0.7062256809338522| 3.090909090909091|
|         Drew Brees|  2020|       97| 8.083333333333334|             275|22.916666666666668|          390|              32.5|            2942.0|245.16666666666666|              24|                2.0|               6.0|                0.5|   0.7051282051282052|               4.0|
|         Joe Burrow|  2021|      143|            8.9375|             366|            22.875|          520|              32.5|            4611.0|          288.1875|              34|              2.125|              14.0|              0.875|   0.7038461538461539|2.4285714285714284|
|         Derek Carr|  2019|      147|            9.1875|             361|           22.5625|          513|           32.0625|            4054.0|           253.375|              21|             1.3125|               8.0|                0.5|   0.7037037037037037|             2.625|
|      Jake Browning|  2023|      117|              13.0|             171|              19.0|          243|              27.0|            1936.0|215.11111111111111|              12| 1.3333333333333333|               7.0| 0.7777777777777778|   0.7037037037037037|1.7142857142857142|
|       Chase Daniel|  2019|       20| 6.666666666666667|              45|              15.0|           64|21.333333333333332|             435.0|             145.0|               3|                1.0|               2.0| 0.6666666666666666|             0.703125|               1.5|
|     Ryan Tannehill|  2019|      128|10.666666666666666|             201|             16.75|          286|23.833333333333332|            2742.0|             228.5|              22| 1.8333333333333333|               6.0|                0.5|   0.7027972027972028|3.6666666666666665|
|     Deshaun Watson|  2020|      145|            9.0625|             382|            23.875|          544|              34.0|            4823.0|          301.4375|              33|             2.0625|               7.0|             0.4375|   0.7022058823529411| 4.714285714285714|
|         Alex Smith|  2012|       63|               6.3|             153|              15.3|          218|              21.8|            1737.0|             173.7|              13|                1.3|               5.0|                0.5|   0.7018348623853211|               2.6|
|       Kirk Cousins|  2018|      143|            8.9375|             425|           26.5625|          606|            37.875|            4298.0|           268.625|              30|              1.875|              10.0|              0.625|   0.7013201320132013|               3.0|
|       Jamie Martin|  2005|       92|              11.5|             124|              15.5|          177|            22.125|            1277.0|           159.625|               5|              0.625|               7.0|              0.875|   0.7005649717514124|0.7142857142857143|
|         Drew Brees|  2016|      148|              9.25|             471|           29.4375|          673|           42.0625|            5208.0|             325.5|              37|             2.3125|              15.0|             0.9375|   0.6998514115898959| 2.466666666666667|
|          Tony Romo|  2014|      133| 8.866666666666667|             304|20.266666666666666|          435|              29.0|            3705.0|             247.0|              34| 2.2666666666666666|               9.0|                0.6|   0.6988505747126437|3.7777777777777777|
|          Matt Ryan|  2016|      142|             8.875|             373|           23.3125|          534|            33.375|            4944.0|             309.0|              38|              2.375|               7.0|             0.4375|   0.6985018726591761| 5.428571428571429|
|       Kirk Cousins|  2015|      145|            9.0625|             379|           23.6875|          543|           33.9375|            4166.0|           260.375|              29|             1.8125|              11.0|             0.6875|   0.6979742173112339|2.6363636363636362|
|         Geno Smith|  2022|      160| 9.411764705882353|             399|23.470588235294116|          572| 33.64705882352941|            4282.0|251.88235294117646|              30| 1.7647058823529411|              11.0| 0.6470588235294118|   0.6975524475524476| 2.727272727272727|
|       Chase Daniel|  2018|       38|               9.5|              53|             13.25|           76|              19.0|             515.0|            128.75|               3|               0.75|               2.0|                0.5|   0.6973684210526315|               1.5|
|       Carson Wentz|  2018|       93| 8.454545454545455|             279|25.363636363636363|          401| 36.45454545454545|            3074.0|279.45454545454544|              21| 1.9090909090909092|               7.0| 0.6363636363636364|   0.6957605985037406|               3.0|
|       Dak Prescott|  2023|      164| 9.647058823529411|             410| 24.11764705882353|          590|34.705882352941174|            4516.0| 265.6470588235294|              36| 2.1176470588235294|               9.0| 0.5294117647058824|   0.6949152542372882|               4.0|
|      Philip Rivers|  2013|      145|            9.0625|             378|            23.625|          544|              34.0|            4478.0|           279.875|              32|                2.0|              11.0|             0.6875|   0.6948529411764706| 2.909090909090909|
|          Tony Romo|  2010|       24|               4.0|             148|24.666666666666668|          213|              35.5|            1605.0|             267.5|              11| 1.8333333333333333|               7.0| 1.1666666666666667|   0.6948356807511737|1.5714285714285714|
|       Kirk Cousins|  2023|       36|               4.5|             216|              27.0|          311|            38.875|            2331.0|           291.375|              18|               2.25|               5.0|              0.625|   0.6945337620578779|               3.6|
|          Matt Ryan|  2018|      145|            9.0625|             422|            26.375|          608|              38.0|            4924.0|            307.75|              35|             2.1875|               7.0|             0.4375|    0.694078947368421|               5.0|
|        Brock Purdy|  2023|      144|               9.0|             308|             19.25|          444|             27.75|            4280.0|             267.5|              31|             1.9375|              11.0|             0.6875|   0.6936936936936937|2.8181818181818183|
|          Jim Sorgi|  2005|       57|              11.4|              43|               8.6|           62|              12.4|             444.0|              88.8|               3|                0.6|               1.0|                0.2|   0.6935483870967742|               3.0|
|     Brandon Weeden|  2015|       45|               7.5|              97|16.166666666666668|          140|23.333333333333332|            1043.0|173.83333333333334|               5| 0.8333333333333334|               2.0| 0.3333333333333333|   0.6928571428571428|               2.5|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+-------------------+------------------+-------------------+---------------------+------------------+
only showing top 40 rows

In this table (above) we see a ranked list of quarterback's seasons, according to their completion percentage. The completion percentage is the sum of touchdowns over the sum of attempts, showing the percentage of the quarteback's attempts resulted in touchdowns. The highest ranked quarterback season by completion percentage was C.J. Beathard in 2023. Drew Brees is also notable for having seven of the top 40 quarterback seasons by completion percentage.

In [51]:
#include only player-season combinations with at leat 50 total attempts
#sort by touchdowns-to-interceptions ratio and return top 40 values
nfl_summary_sql.filter(nfl_summary_sql["sum(attempts)"] >= 50) \
    .sort(F.col("td_int_ratio").desc_nulls_last()).show(40)

+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+-------------------+---------------------+-----------------+
|player_display_name|season|sum(week)|         avg(week)|sum(completions)|  avg(completions)|sum(attempts)|     avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|  avg(passing_tds)|sum(interceptions)| avg(interceptions)|completion_percentage|     td_int_ratio|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+-------------------+---------------------+-----------------+
|          Tom Brady|  2016|      134|11.166666666666666|             291|             24.25|          432|              36.0|            3554.0| 296.1666666666667|              28|2.3333333333333335|               2.0|0.16666666666666666|   0.6736111111111112|             14.0|
|         Nick Foles|  2013|      129| 9.923076923076923|             203|15.615384615384615|          317|24.384615384615383|            2891.0| 222.3846153846154|              27| 2.076923076923077|               2.0|0.15384615384615385|   0.6403785488958991|             13.5|
|        Josh McCown|  2013|       92|              11.5|             149|            18.625|          224|              28.0|            1829.0|           228.625|              13|             1.625|               1.0|              0.125|   0.6651785714285714|             13.0|
|      Aaron Rodgers|  2018|      146|             9.125|             372|             23.25|          597|           37.3125|            4442.0|           277.625|              25|            1.5625|               2.0|              0.125|   0.6231155778894473|             12.5|
|        Damon Huard|  2006|       69|               6.9|             148|              14.8|          244|              24.4|            1878.0|             187.8|              11|               1.1|               1.0|                0.1|   0.6065573770491803|             11.0|
|      Aaron Rodgers|  2020|      148|              9.25|             372|             23.25|          526|            32.875|            4299.0|          268.6875|              48|               3.0|               5.0|             0.3125|   0.7072243346007605|              9.6|
|      Aaron Rodgers|  2021|      149|            9.3125|             366|            22.875|          531|           33.1875|            4115.0|          257.1875|              37|            2.3125|               4.0|               0.25|   0.6892655367231638|             9.25|
|          Tom Brady|  2010|      148|              9.25|             324|             20.25|          492|             30.75|            3900.0|            243.75|              36|              2.25|               4.0|               0.25|   0.6585365853658537|              9.0|
|      Jake Delhomme|  2007|        6|               2.0|              55|18.333333333333332|           86|28.666666666666668|             617.0|205.66666666666666|               8|2.6666666666666665|               1.0| 0.3333333333333333|   0.6395348837209303|              8.0|
|      Aaron Rodgers|  2014|      144|               9.0|             341|           21.3125|          520|              32.5|            4381.0|          273.8125|              38|             2.375|               5.0|             0.3125|   0.6557692307692308|              7.6|
|      Aaron Rodgers|  2011|      128| 8.533333333333333|             342|              22.8|          501|              33.4|            4636.0|309.06666666666666|              45|               3.0|               6.0|                0.4|   0.6826347305389222|              7.5|
|         Drew Brees|  2019|      119|10.818181818181818|             281|25.545454545454547|          378| 34.36363636363637|            2979.0| 270.8181818181818|              27|2.4545454545454546|               4.0|0.36363636363636365|   0.7433862433862434|             6.75|
|      Aaron Rodgers|  2019|      142|             8.875|             353|           22.0625|          569|           35.5625|            4002.0|           250.125|              26|             1.625|               4.0|               0.25|   0.6203866432337434|              6.5|
|         Drew Brees|  2018|      130| 8.666666666666666|             364|24.266666666666666|          489|              32.6|            3992.0| 266.1333333333333|              32|2.1333333333333333|               5.0| 0.3333333333333333|   0.7443762781186094|              6.4|
|    Patrick Mahomes|  2020|      126|               8.4|             390|              26.0|          588|              39.2|            4740.0|             316.0|              38| 2.533333333333333|               6.0|                0.4|   0.6632653061224489|6.333333333333333|
|          Tom Brady|  2007|      143|            8.9375|             398|            24.875|          578|            36.125|            4806.0|           300.375|              50|             3.125|               8.0|                0.5|   0.6885813148788927|             6.25|
|     Russell Wilson|  2019|      142|             8.875|             341|           21.3125|          516|             32.25|            4110.0|           256.875|              31|            1.9375|               5.0|             0.3125|   0.6608527131782945|              6.2|
|   Matthew Stafford|  2010|       26|               6.5|              57|             14.25|           96|              24.0|             535.0|            133.75|               6|               1.5|               1.0|               0.25|              0.59375|              6.0|
|      David Garrard|  2007|      105|              8.75|             208|17.333333333333332|          325|27.083333333333332|            2509.0|209.08333333333334|              18|               1.5|               3.0|               0.25|                 0.64|              6.0|
|      Lamar Jackson|  2019|      128| 8.533333333333333|             265|17.666666666666668|          401|26.733333333333334|            3127.0|208.46666666666667|              36|               2.4|               6.0|                0.4|   0.6608478802992519|              6.0|
|       Dak Prescott|  2016|      146|             9.125|             311|           19.4375|          459|           28.6875|            3667.0|          229.1875|              23|            1.4375|               4.0|               0.25|   0.6775599128540305|             5.75|
|      Aaron Rodgers|  2016|      149|            9.3125|             401|           25.0625|          610|            38.125|            4428.0|            276.75|              40|               2.5|               7.0|             0.4375|   0.6573770491803279|5.714285714285714|
|     Peyton Manning|  2013|      144|               9.0|             450|            28.125|          659|           41.1875|            5477.0|          342.3125|              55|            3.4375|              10.0|              0.625|   0.6828528072837633|              5.5|
|          Matt Ryan|  2016|      142|             8.875|             373|           23.3125|          534|            33.375|            4944.0|             309.0|              38|             2.375|               7.0|             0.4375|   0.6985018726591761|5.428571428571429|
|         Alex Smith|  2017|      126|               8.4|             341|22.733333333333334|          505|33.666666666666664|            4042.0|269.46666666666664|              26|1.7333333333333334|               5.0| 0.3333333333333333|   0.6752475247524753|              5.2|
|    Patrick Mahomes|  2019|      124| 8.857142857142858|             319|22.785714285714285|          484| 34.57142857142857|            4031.0|287.92857142857144|              26|1.8571428571428572|               5.0|0.35714285714285715|   0.6590909090909091|              5.2|
|          Tom Brady|  2015|      149|            9.3125|             402|            25.125|          624|              39.0|            4770.0|           298.125|              36|              2.25|               7.0|             0.4375|   0.6442307692307693|5.142857142857143|
|          Matt Ryan|  2018|      145|            9.0625|             422|            26.375|          608|              38.0|            4924.0|            307.75|              35|            2.1875|               7.0|             0.4375|    0.694078947368421|              5.0|
|        Jeff Garcia|  2006|      102|             12.75|             116|              14.5|          188|              23.5|            1309.0|           163.625|              10|              1.25|               2.0|               0.25|   0.6170212765957447|              5.0|
|     Russell Wilson|  2018|      146|             9.125|             280|              17.5|          427|           26.6875|            3448.0|             215.5|              35|            2.1875|               7.0|             0.4375|   0.6557377049180327|              5.0|
|         Geno Smith|  2021|       26|               6.5|              65|             16.25|           95|             23.75|             702.0|             175.5|               5|              1.25|               1.0|               0.25|   0.6842105263157895|              5.0|
|      Aaron Rodgers|  2012|      143|            8.9375|             371|           23.1875|          552|              34.5|            4295.0|          268.4375|              39|            2.4375|               8.0|                0.5|   0.6721014492753623|            4.875|
|     Ryan Tannehill|  2020|      149|            9.3125|             315|           19.6875|          481|           30.0625|            3819.0|          238.6875|              34|             2.125|               7.0|             0.4375|   0.6548856548856549|4.857142857142857|
|        Brett Favre|  2009|      144|               9.0|             364|             22.75|          532|             33.25|            4202.0|           262.625|              33|            2.0625|               7.0|             0.4375|   0.6842105263157895|4.714285714285714|
|       Kirk Cousins|  2021|      147|            9.1875|             372|             23.25|          561|           35.0625|            4221.0|          263.8125|              33|            2.0625|               7.0|             0.4375|   0.6631016042780749|4.714285714285714|
|       Carson Wentz|  2017|       95|7.3076923076923075|             265|20.384615384615383|          440| 33.84615384615385|            3296.0|253.53846153846155|              33|2.5384615384615383|               7.0| 0.5384615384615384|   0.6022727272727273|4.714285714285714|
|     Deshaun Watson|  2020|      145|            9.0625|             382|            23.875|          544|              34.0|            4823.0|          301.4375|              33|            2.0625|               7.0|             0.4375|   0.7022058823529411|4.714285714285714|
|         Derek Carr|  2016|      126|               8.4|             357|              23.8|          560|37.333333333333336|            3937.0|262.46666666666664|              28|1.8666666666666667|               6.0|                0.4|               0.6375|4.666666666666667|
|     Jameis Winston|  2021|       30| 4.285714285714286|              95|13.571428571428571|          161|              23.0|            1170.0|167.14285714285714|              14|               2.0|               3.0|0.42857142857142855|   0.5900621118012422|4.666666666666667|
|        C.J. Stroud|  2023|      133| 8.866666666666667|             319|21.266666666666666|          499|33.266666666666666|            4108.0| 273.8666666666667|              23|1.5333333333333334|               5.0| 0.3333333333333333|   0.6392785571142284|              4.6|
+-------------------+------+---------+------------------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+-------------------+---------------------+-----------------+
only showing top 40 rows

In this table (above) we see a ranked list of quarterback's seasons, according to their touchdown to interception ratios. The highest ranked quarterback season by touchdown to interception ratio was Tom Brady in 2016, and he has an additional three seasons in this top 40. Aaron Rodgers is also notable for appearing in the top 40 touchdown to interception ratios seven times. Drew Brees appears on this list twice after appearing on the completion percentage list seven times.